FROM lblanp/ros_base_noetic_arm64v8

# Install dependencies
RUN pip3 install --no-cache-dir --force \
    tornado \
    simplejpeg \
    psutil

# Get source code
WORKDIR $WORKSPACE
RUN mkdir -p src \
    && cd src \
    && git clone https://github.com/lbl-anp/rosboard.git \
    && cd rosboard \
    && git checkout 86ad41a88d72aa3bf109ec3f50f627fcc4d91f49

# Build ros workspace
RUN /wsutil.sh --build_workflow $WORKSPACE

# Webserver
EXPOSE 8888
