organization: lblanp
max_num_workers: 4
cross_platform: True
push: True
stages:
  - name: ROS base images
    context: ./ros_base
    paths:
    - ros_base
  - name: Other images
    context: ./
    paths:
      - outsight_alb_driver
      - cartographer
      - cv_camera
      - potree_converter
      - ros_board
      - ros_viz
      - livox
