FROM lblanp/ros_base_noetic_x86

# Install dependencies
RUN apt-get update \
    && apt-get install -q -y --no-install-recommends \
        ros-$ROS_DISTRO-rviz \
        ros-$ROS_DISTRO-rqt \
        ros-$ROS_DISTRO-rqt-common-plugins \
        ros-$ROS_DISTRO-camera-calibration \
    && rm -rf /var/lib/apt/lists/*
