# This workflow will build and push to dockerhub. It uses the parallel-docker-build
# python package to follow the workflow.yaml in images to build the base images
# first and then build the rest of the images in parallel.
# Based on: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

name: Build docker images in parallel and push to pypi

# Run on push/PR/manually BUT only uploads with a tag (see below)
on:
  push:
    # tags: ["v*"]
    # branches: [$default-branch]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install parallel_docker_build
        run: |
          python -m pip install --upgrade pip
          pip install parallel-docker-build
      - name: Log in to Docker Hub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Cache docker image layers
        uses: actions/cache@v2
        with:
          path: |
            /var/lib/docker/image
            /var/lib/docker/overlay2
      - name: Run docker build and push workflow
        run: |
          cd images
          parallel-docker-build workflow workflow.yaml
